window.I18N_PAGE_DICT = {
  'founder.back': { en: 'Back to home', ar: 'العودة إلى الرئيسية' },
  'founder.tag': { en: 'Meet the founder', ar: 'تعرف على المؤسس' },
  'founder.uploadPhoto': { en: 'Upload photo', ar: 'رفع صورة' },
  'founder.title': { en: 'Founder, iHealth Academy', ar: 'مؤسس أكاديمية آي هيلث' },
  'founder.bio1': { en: 'Dr. Musab M. Ahmed is a physician, radiology resident, medical insurance professional, and healthcare educator committed to making high-quality medical education more practical, accessible, and future-ready.', ar: 'الدكتور مصعب م. أحمد طبيب ومقيم أشعة ومحترف في التأمين الطبي ومربٍ في مجال الرعاية الصحية، ملتزم بجعل التعليم الطبي عالي الجودة أكثر عملية وسهولة في الوصول ومستعدًا للمستقبل.' },
  'founder.bio2': { en: 'With experience spanning diagnostic radiology, healthcare insurance, clinical decision-making, and healthcare quality, he founded iHealth Academy with one simple belief:', ar: 'بخبرة تمتد عبر الأشعة التشخيصية والتأمين الصحي واتخاذ القرار السريري وجودة الرعاية الصحية، أسس أكاديمية آي هيلث بناءً على قناعة بسيطة واحدة:' },
  'founder.quote': { en: '"Learning should not only help healthcare professionals pass examinations — it should help them make better decisions, provide safer patient care, and build meaningful careers."', ar: '"يجب ألا يساعد التعلم أخصائيي الرعاية الصحية على اجتياز الامتحانات فقط — بل يجب أن يساعدهم على اتخاذ قرارات أفضل، وتقديم رعاية أكثر أمانًا للمرضى، وبناء مسيرات مهنية ذات معنى."' },
  'founder.bio3': { en: 'At iHealth Academy, every course is designed to bridge the gap between theory and real-world practice, empowering healthcare professionals with knowledge they can apply confidently from day one.', ar: 'في أكاديمية آي هيلث، كل دورة مصممة لسد الفجوة بين النظرية والممارسة الواقعية، لتمكين أخصائيي الرعاية الصحية من معرفة يمكنهم تطبيقها بثقة منذ اليوم الأول.' },
  'founder.bio4': { en: 'As artificial intelligence reshapes healthcare, our commitment remains unchanged: combining human expertise with innovative technology to create a smarter, more effective learning experience — without losing the values that define great healthcare professionals.', ar: 'بينما يعيد الذكاء الاصطناعي تشكيل الرعاية الصحية، يبقى التزامنا ثابتًا: الجمع بين الخبرة البشرية والتقنية المبتكرة لخلق تجربة تعلم أذكى وأكثر فعالية — دون فقدان القيم التي تُعرّف أفضل أخصائيي الرعاية الصحية.' },
  'founder.visionTitle': { en: 'Our Vision', ar: 'رؤيتنا' },
  'founder.visionDesc': { en: 'To become one of the world\'s most trusted digital healthcare learning platforms, empowering healthcare professionals through innovation, evidence-based education, and responsible artificial intelligence.', ar: 'أن نصبح واحدة من أكثر منصات التعلم الصحي الرقمي الموثوقة في العالم، لتمكين أخصائيي الرعاية الصحية من خلال الابتكار والتعليم القائم على الأدلة والذكاء الاصطناعي المسؤول.' },
  'founder.missionTitle': { en: 'Our Mission', ar: 'مهمتنا' },
  'founder.missionDesc': { en: 'We strive to deliver practical, high-quality healthcare education that enables professionals to learn efficiently, think critically, and excel in their careers. By integrating expert knowledge, modern technology, and AI-powered learning, we aim to make continuous professional development more accessible, engaging, and impactful for healthcare professionals worldwide.', ar: 'نسعى لتقديم تعليم صحي عملي وعالي الجودة يمكّن المحترفين من التعلم بكفاءة والتفكير النقدي والتفوق في مسيرتهم المهنية. من خلال دمج المعرفة الخبيرة والتقنية الحديثة والتعلم المدعوم بالذكاء الاصطناعي، نهدف إلى جعل التطوير المهني المستمر أكثر سهولة وجاذبية وتأثيرًا لأخصائيي الرعاية الصحية حول العالم.' },
  'founder.whyTitle': { en: 'Why iHealth Academy?', ar: 'لماذا أكاديمية آي هيلث؟' },
  'founder.why1': { en: 'Evidence-based medical education', ar: 'تعليم طبي قائم على الأدلة' },
  'founder.why2': { en: 'Practical, career-focused learning', ar: 'تعلم عملي يركز على المسيرة المهنية' },
  'founder.why3': { en: 'Expert-led training and mentorship', ar: 'تدريب وإرشاد بقيادة خبراء' },
  'founder.why4': { en: 'AI-enhanced learning experience', ar: 'تجربة تعلم معززة بالذكاء الاصطناعي' },
  'founder.why5': { en: 'Continuous innovation and lifelong professional development', ar: 'ابتكار مستمر وتطور مهني مدى الحياة' },
  'founder.banner': { en: 'Learn. Innovate. Transform Healthcare.', ar: 'تعلّم. ابتكر. غيّر الرعاية الصحية.' },
  'footer.meetFounder': { en: 'Meet the Founder', ar: 'تعرف على المؤسس' },
};

AOS.init({ duration: 700, easing: 'ease', once: true, offset: 80 });
