window.I18N_PAGE_DICT = {
  'legal.back': { en: 'Back to home', ar: 'العودة إلى الرئيسية' },
  'legal.tag': { en: 'Legal Center', ar: 'المركز القانوني' },
  'legal.title': { en: 'Terms and conditions.', ar: 'الشروط والأحكام.' },
  'legal.updated': { en: 'Last updated: July 2026', ar: 'آخر تحديث: يوليو 2026' },
  'legal.intro': { en: 'These terms govern your use of iHealth Academy — our courses, quizzes, certificates, tools, and community features. By creating an account or using the site, you agree to the terms below.', ar: 'تحكم هذه الشروط استخدامك لأكاديمية آي هيلث — دوراتنا واختباراتنا وشهاداتنا وأدواتنا وميزات المجتمع. من خلال إنشاء حساب أو استخدام الموقع، فإنك توافق على الشروط أدناه.' },
  'legal.nav1': { en: 'Acceptance of terms', ar: 'قبول الشروط' },
  'legal.nav2': { en: 'Using the platform', ar: 'استخدام المنصة' },
  'legal.nav3': { en: 'Accounts', ar: 'الحسابات' },
  'legal.nav4': { en: 'Certificates', ar: 'الشهادات' },
  'legal.nav5': { en: 'Payments & refunds', ar: 'المدفوعات والاسترداد' },
  'legal.nav6': { en: 'Acceptable use', ar: 'الاستخدام المقبول' },
  'legal.nav7': { en: 'Intellectual property', ar: 'الملكية الفكرية' },
  'legal.nav8': { en: 'Third-party services', ar: 'خدمات الطرف الثالث' },
  'legal.nav9': { en: 'Disclaimers & liability', ar: 'إخلاء المسؤولية والمسؤولية القانونية' },
  'legal.nav10': { en: 'Changes to these terms', ar: 'التغييرات على هذه الشروط' },
  'legal.nav11': { en: 'Contact us', ar: 'تواصل معنا' },
  'legal.h1': { en: '1. Acceptance of terms', ar: '1. قبول الشروط' },
  'legal.p1': { en: 'By accessing or using iHealth Academy, you agree to be bound by these Terms and Conditions and our Privacy Policy. If you do not agree, please do not use the platform.', ar: 'من خلال الوصول إلى أكاديمية آي هيلث أو استخدامها، فإنك توافق على الالتزام بهذه الشروط والأحكام وسياسة الخصوصية الخاصة بنا. إذا كنت لا توافق، يرجى عدم استخدام المنصة.' },
  'legal.h2': { en: '2. Using the platform', ar: '2. استخدام المنصة' },
  'legal.p2': { en: 'iHealth Academy provides courses, quizzes, practice tools, and career resources for healthcare professionals and students. Content is provided for educational purposes and is updated regularly as new specialties and modules are added.', ar: 'تقدم أكاديمية آي هيلث دورات واختبارات وأدوات تدريب وموارد مهنية لأخصائيي وطلاب الرعاية الصحية. يُقدَّم المحتوى لأغراض تعليمية ويُحدَّث بانتظام مع إضافة تخصصات ووحدات جديدة.' },
  'legal.h3': { en: '3. Accounts', ar: '3. الحسابات' },
  'legal.p3': { en: 'You are responsible for keeping your account details accurate and for any activity that happens under your account. Let us know right away if you suspect unauthorized use.', ar: 'أنت مسؤول عن الحفاظ على دقة بيانات حسابك وعن أي نشاط يحدث تحت حسابك. أخبرنا فورًا إذا اشتبهت في استخدام غير مصرح به.' },
  'legal.h4': { en: '4. Certificates', ar: '4. الشهادات' },
  'legal.p4': { en: 'Certificates of completion issued on iHealth Academy confirm that you finished a course or module on our platform. They are not accredited qualifications and are not a substitute for official board, college, or regulatory certification.', ar: 'تؤكد شهادات الإتمام الصادرة عن أكاديمية آي هيلث أنك أنهيت دورة أو وحدة على منصتنا. وهي ليست مؤهلات معتمدة ولا تُغني عن الشهادات الرسمية الصادرة عن البورد أو الكلية أو الجهات التنظيمية.' },
  'legal.h5': { en: '5. Payments & refunds', ar: '5. المدفوعات والاسترداد' },
  'legal.p5': { en: "Paid modules (such as the Insurance bonus module) are processed through PayPal. Access is granted after a completed purchase. Because access unlocks digital content immediately, purchases are generally non-refundable — if something went wrong with your payment, contact us and we'll make it right.", ar: 'تتم معالجة الوحدات المدفوعة (مثل الوحدة الإضافية للتأمين) عبر PayPal. يُمنح الوصول بعد إتمام عملية الشراء. ونظرًا لأن الوصول يفتح المحتوى الرقمي فورًا، فإن المشتريات غير قابلة للاسترداد بشكل عام — إذا حدث خطأ ما في عملية الدفع، تواصل معنا وسنقوم بمعالجة الأمر.' },
  'legal.h6': { en: '6. Acceptable use', ar: '6. الاستخدام المقبول' },
  'legal.p6': { en: "Don't misuse the platform — this includes attempting to bypass access controls, sharing paid content or your account with others, or using the site in a way that disrupts other learners.", ar: 'يُرجى عدم إساءة استخدام المنصة — ويشمل ذلك محاولة تجاوز ضوابط الوصول، أو مشاركة المحتوى المدفوع أو حسابك مع آخرين، أو استخدام الموقع بطريقة تُعطّل المتعلمين الآخرين.' },
  'legal.h7': { en: '7. Intellectual property', ar: '7. الملكية الفكرية' },
  'legal.p7': { en: 'All course content, text, graphics, and branding on iHealth Academy belong to iHealth Academy or its licensors. You may use it for your own personal learning, but not republish, resell, or redistribute it without permission.', ar: 'جميع محتويات الدورات والنصوص والرسومات والعلامة التجارية على أكاديمية آي هيلث مملوكة لأكاديمية آي هيلث أو للجهات المرخِّصة لها. يمكنك استخدامها لتعلمك الشخصي، لكن لا يجوز إعادة نشرها أو بيعها أو توزيعها دون إذن.' },
  'legal.h8': { en: '8. Third-party services', ar: '8. خدمات الطرف الثالث' },
  'legal.p8': { en: 'Some features rely on third-party services — payment processing via PayPal, application forms via Formspree, and links to our social media channels. Your use of those services is subject to their own terms and privacy policies.', ar: 'تعتمد بعض الميزات على خدمات طرف ثالث — معالجة الدفع عبر PayPal، ونماذج التقديم عبر Formspree، وروابط قنوات التواصل الاجتماعي الخاصة بنا. يخضع استخدامك لتلك الخدمات لشروطها وسياسات الخصوصية الخاصة بها.' },
  'legal.h9': { en: '9. Disclaimers & liability', ar: '9. إخلاء المسؤولية والمسؤولية القانونية' },
  'legal.p9': { en: 'iHealth Academy is provided "as is," without warranties of any kind. Course content is for educational purposes and should not replace professional medical, legal, or clinical judgment. To the fullest extent permitted by law, iHealth Academy is not liable for indirect or consequential damages arising from your use of the platform.', ar: 'تُقدَّم أكاديمية آي هيلث "كما هي" دون أي ضمانات من أي نوع. محتوى الدورات لأغراض تعليمية ولا ينبغي أن يحل محل الحكم الطبي أو القانوني أو السريري المهني. وإلى أقصى حد يسمح به القانون، لا تتحمل أكاديمية آي هيلث المسؤولية عن أي أضرار غير مباشرة أو تبعية ناشئة عن استخدامك للمنصة.' },
  'legal.h10': { en: '10. Changes to these terms', ar: '10. التغييرات على هذه الشروط' },
  'legal.p10': { en: 'We may update these terms from time to time as the platform grows. We\'ll update the "Last updated" date above when we do, and continued use of the site after a change means you accept the new terms.', ar: 'قد نُحدّث هذه الشروط من وقت لآخر مع نمو المنصة. سنقوم بتحديث تاريخ "آخر تحديث" أعلاه عند القيام بذلك، واستمرار استخدامك للموقع بعد أي تغيير يعني موافقتك على الشروط الجديدة.' },
  'legal.h11': { en: '11. Contact us', ar: '11. تواصل معنا' },
  'legal.p11': { en: 'Questions about these terms? Reach us any time at <a href="mailto:info@ihealthacademy.com">info@ihealthacademy.com</a>.', ar: 'لديك أسئلة حول هذه الشروط؟ تواصل معنا في أي وقت عبر <a href="mailto:info@ihealthacademy.com">info@ihealthacademy.com</a>.' },
};

AOS.init({ duration: 700, easing: 'ease', once: true, offset: 80 });
